routes/web.php
<?php

use App\Http\Controllers\API;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\SocialAuthController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MeetingController;
use App\Http\Controllers\ReportUserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\FrontCMSController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.index');
});

Auth::routes();
Route::get('activate', [AuthController::class, 'verifyAccount']);

Route::get('/home', [HomeController::class, 'index']);
Route::post('update-language', [UserController::class, 'updateLanguage'])->middleware('auth')->name('update-language');

// Impersonate Logout
Route::get('/users/impersonate-logout',
    [UserController::class, 'userImpersonateLogout'])->name('impersonate.userLogout');

Route::middleware(['user.activated', 'auth'])->group(function () {
    //view routes
    Route::get('/conversations',
        [ChatController::class, 'index'])->name('conversations')->middleware('permission:manage_conversations');
    Route::get('profile', [UserController::class, 'getProfile']);
    Route::get('logout', [LoginController::class, 'logout']);

    //get all user list for chat
    Route::get('users-list', [API\UserAPIController::class, 'getUsersList']);
    Route::get('get-users', [API\UserAPIController::class, 'getUsers'])->name('get-users')->name('get-users');
    Route::delete('remove-profile-image',
        [API\UserAPIController::class, 'removeProfileImage'])->name('remove-profile-image');
    /** Change password */
    Route::post('change-password', [API\UserAPIController::class, 'changePassword'])->name('change-password');
    Route::get('conversations/{ownerId}/archive-chat', [API\UserAPIController::class, 'archiveChat'])->name('conversations.archive-chat');
    Route::get('conversations/{ownerId}/un-archive-chat', [API\UserAPIController::class, 'unArchiveChat'])->name('conversations.un-archive-chat');

    Route::get('get-profile', [API\UserAPIController::class, 'getProfile']);
    Route::post('profile', [API\UserAPIController::class, 'updateProfile'])->name('update.profile');
    Route::post('update-last-seen', [API\UserAPIController::class, 'updateLastSeen'])->name('update-last-seen');

    Route::post('send-message',
        [API\ChatAPIController::class, 'sendMessage'])->name('conversations.store')->middleware('sendMessage');
    Route::get('users/{id}/conversation', [API\UserAPIController::class, 'getConversation'])->name('users.conversation');
    Route::get('conversations-list', [API\ChatAPIController::class, 'getLatestConversations'])->name('conversations-list');
    Route::get('archive-conversations', [API\ChatAPIController::class, 'getArchiveConversations'])->name('archive-conversations');
    Route::post('read-message', [API\ChatAPIController::class, 'updateConversationStatus'])->name('read-message');
    Route::post('file-upload', [API\ChatAPIController::class, 'addAttachment'])->name('file-upload');
    Route::post('image-upload', [API\ChatAPIController::class, 'imageUpload'])->name('image-upload');
    Route::get('conversations/{userId}/delete', [API\ChatAPIController::class, 'deleteConversation'])->name('conversations.destroy');
    Route::post('conversations/message/{conversation}/delete', [API\ChatAPIController::class, 'deleteMessage'])->name('conversations.message-conversation.delete');
    Route::post('conversations/{conversation}/delete', [API\ChatAPIController::class, 'deleteMessageForEveryone']);
    Route::get('/conversations/{conversation}', [API\ChatAPIController::class, 'show']);
    Route::post('send-chat-request', [API\ChatAPIController::class, 'sendChatRequest'])->name('send-chat-request');
    Route::post('accept-chat-request',
        [API\ChatAPIController::class, 'acceptChatRequest'])->name('accept-chat-request');
    Route::post('decline-chat-request',
        [API\ChatAPIController::class, 'declineChatRequest'])->name('decline-chat-request');

    /** Web Notifications */
    Route::put('update-web-notifications', [API\UserAPIController::class, 'updateNotification'])->name('update-web-notifications');

    /** BLock-Unblock User */
    Route::put('users/{user}/block-unblock', [API\BlockUserAPIController::class, 'blockUnblockUser'])->name('users.block-unblock');
    Route::get('blocked-users', [API\BlockUserAPIController::class, 'blockedUsers']);

    /** My Contacts */
    Route::get('my-contacts', [API\UserAPIController::class, 'myContacts'])->name('my-contacts');

    /** Groups API */
    Route::post('groups', [API\GroupAPIController::class, 'create'])->name('groups.create');
    Route::post('groups/{group}', [API\GroupAPIController::class, 'update'])->name('groups.update');
    Route::get('groups', [API\GroupAPIController::class, 'index'])->name('groups.index');
    Route::get('groups/{group}', [API\GroupAPIController::class, 'show'])->name('group.show');
    Route::put('groups/{group}/add-members', [API\GroupAPIController::class, 'addMembers'])->name('groups-group.add-members');
    Route::delete('groups/{group}/members/{user}', [API\GroupAPIController::class, 'removeMemberFromGroup'])->name('group-from-member-remove');
    Route::delete('groups/{group}/leave', [API\GroupAPIController::class, 'leaveGroup'])->name('groups.leave');
    Route::delete('groups/{group}/remove', [API\GroupAPIController::class, 'removeGroup'])->name('group-remove');
    Route::put('groups/{group}/members/{user}/make-admin', [API\GroupAPIController::class, 'makeAdmin'])->name('groups.members.make-admin');
    Route::put('groups/{group}/members/{user}/dismiss-as-admin', [API\GroupAPIController::class, 'dismissAsAdmin'])->name('groups.members.dismiss-as-admin');
    Route::get('users-blocked-by-me', [API\BlockUserAPIController::class, 'blockUsersByMe']);

    Route::get('notification/{notification}/read', [API\NotificationController::class, 'readNotification'])->name('notification.read-notification');
    Route::get('notification/read-all', [API\NotificationController::class, 'readAllNotification'])->name('read-all-notification');

    Route::put('update-player-id', [API\UserAPIController::class, 'updatePlayerId'])->name('update-player-id');
    //set user custom status route
    Route::post('set-user-status', [API\UserAPIController::class, 'setUserCustomStatus'])->name('set-user-status');
    Route::get('clear-user-status', [API\UserAPIController::class, 'clearUserCustomStatus'])->name('clear-user-status');

    //report user
    Route::post('report-user', [API\ReportUserController::class, 'store'])->name('report-user.store');
});

// users
Route::middleware(['permission:manage_users', 'auth', 'user.activated'])->group(function () {
    Route::resource('users', UserController::class);
    Route::post('users/{user}/active-de-active', [UserController::class, 'activeDeActiveUser'])
        ->name('active-de-active-user');
    Route::post('users/{user}/update', [UserController::class, 'update'])->name('user.update');
    Route::delete('users/{user}/archive', [UserController::class, 'archiveUser'])->name('archive-user');
    Route::post('users/restore', [UserController::class, 'restoreUser'])->name('user.restore-user');
    Route::get('users/{user}/login', [UserController::class, 'userImpersonateLogin'])->name('user-impersonate-login');
    Route::post('users/{user}/email-verified', [UserController::class, 'isEmailVerified'])->name('user.email-verified');
});

// roles
Route::middleware(['permission:manage_roles', 'auth', 'user.activated'])->group(function () {
    Route::resource('roles', RoleController::class)->except('update');
    Route::post('roles/{role}/update', [RoleController::class, 'update'])->name('roles.update');
});

// settings
Route::middleware(['permission:manage_settings', 'auth', 'user.activated'])->group(function () {
    Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::post('settings', [SettingsController::class, 'update'])->name('settings.update');
    Route::get('chatSettings', [SettingsController::class, 'chatSettings'])->name('settings.chatSettings');
    Route::post('chatSettings', [SettingsController::class, 'chatSettingsUpdate'])->name('chatSettings.update');
});

// reported-users
Route::middleware(['permission:manage_reported_users', 'auth', 'user.activated'])->group(function () {
    Route::resource('reported-users', ReportUserController::class);
});

// meetings
Route::middleware(['permission:manage_meetings', 'auth', 'user.activated'])->group(function () {
    Route::resource('meetings', MeetingController::class);
    Route::get('meetings/{meeting}/change-status/{status}',
        [MeetingController::class, 'changeMeetingStatus'])->name('meeting.change-meeting-status');
    Route::get('member/meetings', [MeetingController::class, 'showMemberMeetings'])->name('meetings.member_index');
});

Route::middleware('web')->group(function () {
    Route::get('login/{provider}', [SocialAuthController::class, 'redirect']);
    Route::get('login/{provider}/callback', [SocialAuthController::class, 'callback']);
});

Route::middleware(['permission:manage_front_cms', 'auth', 'user.activated'])->group(function () {
    Route::get('front-cms', [FrontCMSController::class, 'frontCms'])->name('front.cms');
    Route::post('front-cms', [FrontCMSController::class, 'updateFrontCms'])->name('front.cms.update');
});

app/Http/Controllers/MeetingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMeetingRequest;
use App\Models\User;
use App\Models\ZoomMeeting;
use App\Queries\MeetingDataTable;
use App\Repositories\MeetingRepository;
use Auth;
use DataTables;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Laracasts\Flash\Flash;

/**
 * Class MeetingController
 */
class MeetingController extends AppBaseController
{
    /**
     * @var MeetingRepository
     */
    private $meetingRepository;

    /**
     * MeetingController constructor.
     *
     * @param  MeetingRepository  $meetingRepository
     */
    public function __construct(MeetingRepository $meetingRepository)
    {
        $this->meetingRepository = $meetingRepository;
    }

    /**
     * @param  Request  $request
     * @return Application|Factory|\Illuminate\Contracts\View\View|RedirectResponse
     *
     * @throws Exception
     */
    public function index(Request $request)
    {
        if (getLoggedInUser()->hasRole('Member')) {
            return redirect()->back();
        }

        if ($request->ajax()) {
            return Datatables::of((new MeetingDataTable())->get())->make(true);
        }

        return view('meetings.index');
    }

    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        $timeZones = getTimeZone();
        $users = User::where('id', '!=', Auth::id())->pluck('name', 'id');

        return view('meetings.create', compact('users', 'timeZones'));
    }

    /**
     * @param  int  $meeting
     * @return Application|Factory|\Illuminate\Contracts\View\View|RedirectResponse
     */
    public function edit($meeting)
    {
        $timeZones = getTimeZone();
        $meeting = ZoomMeeting::with('members')->findOrFail($meeting);
        if ($meeting->status == ZoomMeeting::STATUS_FINISHED) {
            Flash::error('Sorry, Can not update finished meeting.');

            return redirect()->route('meetings.index');
        }

        $meetingTimeZone = array_flip($timeZones)[$meeting->time_zone];
        $members = $meeting->members->pluck('id')->toArray();
        $users = User::where('id', '!=', Auth::id())->pluck('name', 'id');

        return view('meetings.edit', compact('users', 'meeting', 'timeZones', 'members', 'meetingTimeZone'));
    }

    /**
     * @param  CreateMeetingRequest  $request
     * @return RedirectResponse
     */
    public function store(CreateMeetingRequest $request): RedirectResponse
    {
        $this->meetingRepository->store($request->all());
        Flash::success('Meeting saved successfully.');

        return redirect()->route('meetings.index');
    }

    /**
     * @param $meeting
     * @param  CreateMeetingRequest  $request
     * @return RedirectResponse
     */
    public function update($meeting, CreateMeetingRequest $request): RedirectResponse
    {
        $this->meetingRepository->updateZoomMeeting($meeting, $request->all());
        Flash::success('Meeting updated successfully.');

        return redirect()->route('meetings.index');
    }

    /**
     * @param  Request  $request
     * @return Application|Factory|\Illuminate\Contracts\View\View|RedirectResponse
     *
     * @throws Exception
     */
    public function showMemberMeetings(Request $request)
    {
        if (! getLoggedInUser()->hasRole('Member')) {
            return redirect()->back();
        }

        if ($request->ajax()) {
            return Datatables::of((new MeetingDataTable())->get($member = true))->make(true);
        }

        return view('meetings.members_index');
    }

    /**
     * @param  ZoomMeeting  $meeting
     * @return JsonResponse
     */
    public function destroy(ZoomMeeting $meeting): JsonResponse
    {
        $this->meetingRepository->deleteMeeting($meeting->id);

        return $this->sendSuccess('Meeting deleted successfully.');
    }

    /**
     * @param  ZoomMeeting  $meeting
     * @param $status
     * @return JsonResponse
     */
    public function changeMeetingStatus(ZoomMeeting $meeting, $status): JsonResponse
    {
        $this->meetingRepository->changeMeetingStatus($meeting->id, $status);

        return $this->sendSuccess('Meeting status updated successfully.');
    }
}

resources/views/meetings/create.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.new_meeting') }}
@endsection
@section('page_css')
    <link rel="stylesheet" href="{{ mix('assets/css/admin_panel.css') }}">
@endsection
@section('content')
    <div class="container-fluid page__container">
        <div class="animated fadeIn main-table">
            @include('flash::message')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header page-header">
                            <div class="pull-left page__heading">
                                {{ __('messages.new_meeting') }}
                            </div>
                        </div>
                        <div class="card-body">
                            @include('coreui-templates::common.errors')
                            <form method="post" action="{{ route('meetings.store') }}" id="meetingForm">
                                {{ csrf_field() }}
                                <div class="row">
                                @include('meetings.fields')
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="{{ mix('assets/js/admin/meetings/meetings.js') }}"></script>
@endsection

resources/views/meetings/edit.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.edit_meeting') }}
@endsection
@section('page_css')
    <link rel="stylesheet" href="{{ mix('assets/css/admin_panel.css') }}">
@endsection
@section('content')
    <div class="container-fluid page__container">
        <div class="animated fadeIn main-table">
            @include('flash::message')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header page-header">
                            <div class="pull-left page__heading">
                                {{ __('messages.edit_meeting') }}
                            </div>
                        </div>
                        <div class="card-body">
                            @include('coreui-templates::common.errors')
                                {{ Form::model($meeting, ['route' => ['meetings.update', $meeting->id], 'method' => 'put', 'id'=>'meetingForm']) }}
                                {{ csrf_field() }}
                                <div class="row">
                                    @include('meetings.fields')
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="{{ mix('assets/js/admin/meetings/meetings.js') }}"></script>
@endsection

resources/views/meetings/fields.blade.php
<div class="form-group col-sm-6 login-group__sub-title">
    {!! Form::label('topic', __('messages.meeting.meeting_title').':' )!!}<span class="red">*</span>
    {!! Form::text('topic', isset($meeting) ? $meeting->topic : null, ['class' => 'form-control login-group__input', 'required','placeholder'=>__('messages.meeting.meeting_title')]) !!}
</div>

<div class="form-group col-sm-3 col-md-6 col-lg-6 col-xl-3 login-group__sub-title">
    {!! Form::label('start_time', __('messages.meeting.meeting_date').':' )!!}<span class="red">*</span>
    {!! Form::text('start_time', isset($meeting) ? $meeting->start_time : null, ['class' => 'form-control start-time login-group__input', 'required', 'autocomplete' => 'off','placeholder'=>__('messages.meeting.meeting_date')]) !!}
</div>

<div class="form-group col-sm-6 col-md-6 col-lg-6 col-xl-3">
    {!! Form::label('time_zone', __('messages.meeting.time_zone'),['class' => 'login-group__sub-title']).':' !!}<span class="red">*</span>
    {!! Form::select('time_zone', $timeZones, isset($meetingTimeZone) ? $meetingTimeZone : null, ['class' => 'form-control time-zone', 'placeholder' => __('messages.placeholder.select_time_zone'), 'required' ]) !!}
</div>

<div class="form-group col-sm-6 col-md-6 col-lg-6 col-xl-3 login-group__sub-title">
    {!! Form::label('duration', __('messages.meeting.meeting_duration').':')!!}<span class="red">*</span>
    {!! Form::text('duration', isset($meeting) ? $meeting->duration : null, ['class' => 'form-control login-group__input', 'required', 'onkeyup' => 'if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,"")','placeholder'=>__('messages.meeting.meeting_duration')]) !!}
</div>

<div class="form-group col-sm-6 col-md-6 col-lg-6 col-xl-3 login-group__sub-title">
    {!! Form::label('members',__('messages.meeting.staff_list').':')!!}<span class="red">*</span>
    {!! Form::select('members[]', $users, isset($members) ? $members : null, ['class' => 'form-control members', 'multiple', 'required']) !!}
</div>

<div class="form-group col-sm-6 col-lg-6 col-xl-3">
    <label class="login-group__sub-title">{{ __('messages.meeting.host_video').':' }}</label>
    <span class="red">*</span>
    <div class="d-flex login-group__input align-items-center">
        <div class="custom-control custom-radio mx-2">
            <input type="radio" id="host-enabled" class="custom-control-input" name="host_video" value="1"
                   {{ isset($meeting) ? ($meeting->host_video == 1 ? 'checked' : '') : null }} required>
            <label class="custom-control-label" for="host-enabled"> {{__('messages.meeting.enabled')}}&nbsp; </label>
        </div>
        <div class="custom-control custom-radio mx-2">
            <input type="radio" id="host-disabled" class="custom-control-input" name="host_video"
                   {{ isset($meeting) ? ($meeting->host_video == 0 ? 'checked' : '') : null }} value="0"
                   required {{ empty($meeting) ? 'checked' : '' }}>
            <label class="custom-control-label" for="host-disabled"> {{__('messages.meeting.disabled')}}&nbsp; </label>
        </div>
    </div>
</div>

<div class="form-group col-sm-6 col-lg-6 col-xl-3">
    <label class="login-group__sub-title">{{ __('messages.meeting.client_video').':' }}</label>
    <span class="red">*</span>
    <div class="d-flex login-group__input align-items-center">
        <div class="custom-control custom-radio mx-2">
            <input type="radio" id="enabled" class="custom-control-input" name="participant_video"
                   {{ isset($meeting) ? ($meeting->participant_video == 1 ? 'checked' : '') : null }} value="1"
                   required>
            <label class="custom-control-label" for="enabled"> {{__('messages.meeting.enabled')}}&nbsp; </label>
        </div>
        <div class="custom-control custom-radio mx-2">
            <input type="radio" id="disabled" class="custom-control-input"
                   {{ isset($meeting) ? ($meeting->participant_video == 0 ? 'checked' : '') : null }} name="participant_video"
                   value="0" required {{ empty($meeting) ? 'checked' : '' }}>
            <label class="custom-control-label" for="disabled"> {{__('messages.meeting.disabled')}}&nbsp; </label>
        </div>
    </div>
</div>

<div class="form-group col-sm-12 login-group__sub-title">
    {!! Form::label('agenda',__('messages.meeting.description').':')!!}<span class="red">*</span>
    {{ Form::textarea('agenda', null, ['class' => 'form-control login-group__input', 'required','placeholder'=>__('messages.meeting.description')]) }}
</div>

<div class="form-group col-sm-12 mb-0">
    {{ Form::button(__('messages.save') , ['type'=>'submit','class' => 'btn btn-primary me-1','id'=>'btnSave','data-loading-text'=>"<span class='spinner-border spinner-border-sm'></span> " .__('messages.processing')]) }}
    <a href="{{ route('meetings.index') }}"
            class="btn btn-secondary">{{ __('messages.cancel') }}</a>
</div>

resources/views/meetings/index.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.meetings') }}
@endsection
@section('page_css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/dataTable.min.css') }}"/>
    <link rel="stylesheet" href="{{ mix('assets/css/admin_panel.css') }}">
@endsection
@section('content')
    <div class="container-fluid page__container meetings-container">
        <div class="animated fadeIn main-table">
            @include('flash::message')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header page-header flex-wrap">
                            <div class="pull-left page__heading my-2 me-3">
                                {{ __('messages.meetings') }}
                            </div>
                            <div class="filter-container my-2 ms-auto">
                                <a href="{{ route('meetings.create') }}" class="pull-right btn btn-primary primary-btn">{{ __('messages.new_meeting') }}</a>
                            </div>
                        </div>
                        <div class="card-body">
                            @include('meetings.table')
                            <div class="pull-right me-3">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_js')
    <script type="text/javascript" src="{{ asset('js/dataTable.min.js') }}"></script>
@endsection
@section('scripts')
    <script>
        let defaultImageAvatar = "{{ getDefaultAvatar() }}"
    </script>
    <script src="{{ mix('assets/js/admin/meetings/meetings.js') }}"></script>
    <script src="{{ mix('assets/js/admin/meetings/meeting_index.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/custom-datatables.js') }}"></script>
@endsection

resources/views/meetings/member_table.blade.php
<div class="table-responsive">
    <table class="table table-striped table-bordered" id="memberMeetingTable">
        <thead>
        <th>{{ __('messages.topic') }}</th>
        <th>{{ __('messages.start_time') }}</th>
        <th>{{ __('messages.duration') }}</th>
        <th>{{ __('messages.status') }}</th>
        <th>{{ __('messages.password') }}</th>
        <th>{{ __('messages.join') }}</th>
        </thead>
        <tbody></tbody>
    </table>
</div>

resources/views/meetings/members_index.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.meetings') }}
@endsection
@section('page_css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/dataTable.min.css') }}"/>
@endsection
@section('css')
    <link rel="stylesheet" href="{{ mix('assets/css/admin_panel.css') }}">
@endsection
@section('content')
    <div class="container-fluid page__container">
        <div class="animated fadeIn main-table">
            @include('flash::message')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header page-header">
                            <div class="pull-left page__heading">
                                {{ __('messages.meetings') }}
                            </div>
                        </div>
                        <div class="card-body">
                            @include('meetings.member_table')
                            <div class="pull-right me-3">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_js')
    <script type="text/javascript" src="{{ asset('js/dataTable.min.js') }}"></script>
@endsection
@section('scripts')
    <script src="{{ mix('assets/js/admin/meetings/member_meeting_index.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/custom-datatables.js') }}"></script>
@endsection

resources/views/meetings/table.blade.php
<table class="table table-bordered table-borderless table-responsive-sm table-responsive-lg table-responsive-md table-responsive-xl" id="meetingsTable">
    <thead>
    <tr>
        <th>{{ __('messages.topic') }}</th>
        <th>{{ __('messages.start_time') }}</th>
        <th>{{ __('messages.duration') }}</th>
        <th>{{ __('messages.status') }}</th>
        <th>{{ __('messages.password') }}</th>
        <th>{{ __('messages.action') }}</th>
    </tr>
    </thead>
    <tbody></tbody>
</table>